[package]
name = "game-template"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
self_update = "0.39.0"
winit = "0.29.10"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
